spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  liquibase:
    change-log: db.changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate